[package]
name = "gt7-telemetry"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
cipher = "0.4.4"
dotenv = "0.15.0"
salsa20 = "0.10.2"
serde = "1.0.219"
serde_json = "1.0.140"
sodiumoxide = "0.2.7"
tokio = "1.44.0"
zmq = "0.10.0"
